language: python

python:
    - 3.6
    - 3.5

install:
    - pip install -r requirements.txt

script:
    - djangovar=headless coverage run --source=zincbind,scripts `which django-admin.py` test --pythonpath=. --settings=zincbind.settings

after_success:
  - coveralls
