language: python

python:
    - 3.6

install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt

script:
    - djangovar=headless coverage run --source=core,scripts `which django-admin.py` test ftests.test_scripts core --pythonpath=. --settings=core.settings

after_success:
  - coveralls
