language: python

python:
    - 3.6

install:
    - pip install -r requirements.txt

script:
    - djangovar=headless coverage run --source=core,zinc `which django-admin.py` test --pythonpath=. --settings=core.settings

after_success:
  - coveralls
